import type { Metadata } from "next";

import "./globals.css";

import { EstedadRegular } from "./Fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="fa">
			<body className={`${EstedadRegular} text-text`}>
				{children}
			</body>
		</html>
	);
}
